language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: 2000
env:
  global:
  - DEPLOY_BRANCH="gh-pages"

  - secure: q4Upth3KcB6CSVB/T28c7hEuYU0COT5YL3YRM79RI8VjlLHbRMs+Ioy49tbNROQRrbQB4zATxOpMCQLDQFVgY2YhOvacI83rxJqcXq7C3XTq5iQzXLBdQS06tZ5kNVKuS4pzOxTegtsNSlCY7smwaVfiherR+W2h4hKw975PxUpSqcBscQmq3hpME7gmtj0EdFKEKfftF7O5Zqu/NaklJkCErZOxA3pDZyjbhyQP/Wzfk0rytBRapf3zVc5F49kJgBW6PASu9EGctjetQDleMrxHMJ4RkjTyX3CttK+KPfzALq4+66n9CAdSoKt57cqbP6Vvitvk9ahxoazhGVjGVtTLH+7BAI5h2t35exEmw0oOXDoV2qxz0RRIU/u7t4XLaurBjd1mL5xysXgr8QhcEG0m2tP8spc88LZWqeAUDBNyLPRwzu6XfDAORAX7Xa3v5DGqT6u40e82zUbByHWSqfl0m0JO0RT4Rgzn5zbhzLRE09YyQRjP3zOC8hP3Uso+hD+PI/wndrguF4FbvYWsuQCt9Rliyng7ztm78V3x+/LzF0Fq/qvfGDbt8cXL9jzeL8tUk4F5eaTf7u81IveMBc3XwejIHoz4SbNH07bYS82PPrYcr2xtfPqsBuRg6f9+DpfAXXPBWauRc+WsJuuDae4/DWOb+qI7yjYTccJ3f2Q=
  - secure: S87Mw1Gj+C22oOWMUrEl4tgfN16WH6PXLSztEGZLf+XVPAWLRR/4dMtG5XRVMgA3C29WIoWmAf37jJwOiqEqFzF6E6dOGWRWiA/NuII+u9Z7Xeiz/Bb+aoDrJ4Xr18ZbdQPNhbvsBwTSlwL02OhyNlb7+/H/OdGkTfidcPNyHL1Fvi28GICwUowP+Jny1JyOWVPR5MrzVEVVuefdkxx9WUWsfTJmBIfviQHVsTptkmrGpm/4tT427FPmWfU1jc9AwGuc3rCGQATjK2V3W0G4XuHlfRSrwjmXZ/BHSSfKORkK33p7fsP2rMn9Ye2JE1EKq79BEIu8CCZ9tc+SXK6iGq3jmH/PS9DB6phXOgcCXSEaGn3CXCfhTIXD0ZFOloNP9VWCEbr+BFAnL0F4X+WRLDaOP2opBNEmZ1P75V4gBFpsW81zv5R060WkLm5hL1uYXBYUM8hhaQqui6560B1WCzGhyveAviW+ekE7SW5IR4oOvU7vObl56zPwCyVAKyHom2okmx4D2wpP4TIVW3MsPdG6hXiqrJ02+URh96ZBuiw4MSRIJ6MoYCdPS1ZpK9zJnlHua9q9HeEgd0KfW+9wxW0s5lT6D0ZqGnvHiBBxNUSoAFXOPVeaMBtxoo/oYyrcfnrdcogJ0Ik/pr7JOY6ms0IcJit3HHRwmyf97S2k2uU=
before_install:
# travis_retry may overcome some poor network conditions
- travis_retry pip install -U pip setuptools wheel
install:
- travis_retry pip install -r requirements.txt

# as set up in 'memote.ini' this will create a JSON file in Results
script:
- git checkout master
- memote run

# Changed from 'deploy' to 'after_script' so that we deploy even after failures.
after_script:
- chmod +x scripts/deploy.sh
- scripts/deploy.sh
